In [2]:
%%writefile hi.py

UsageError: %%writefile is a cell magic, but the cell body is empty.


In [3]:
%%writefile hi.py

UsageError: %%writefile is a cell magic, but the cell body is empty.


In [4]:
%%writefile hi.py
"int("Hi")"

Writing hi.py


In [5]:
%%writefile hi.py
print("Hi 0929!")

Overwriting hi.py


In [6]:
run hi.py

Hi 0929!


In [9]:
a=1

In [10]:
b=2

In [8]:
whos

Variable   Type    Data/Info
----------------------------
b          int     2


In [11]:
whos

Variable   Type    Data/Info
----------------------------
a          int     1
b          int     2


In [12]:
pip install Numpy

Note: you may need to restart the kernel to use updated packages.


In [13]:
import numpy as np

In [14]:
np1 = np.array([1,2,3,4])

In [15]:
np2 = np.array((5,6,7,8))

In [16]:
run hi.py

Hi 0929!


In [17]:
np1 = np.array([1,2,3,4])#np.array
np2 = np.array((5,6,7,8))

In [18]:
np1

array([1, 2, 3, 4])

In [19]:
np2

array([5, 6, 7, 8])

In [20]:
print np1

SyntaxError: Missing parentheses in call to 'print'. Did you mean print(np1)? (1070607173.py, line 1)

In [21]:
print(np1)
print(np2)
print(type(np1),type(np2))

[1 2 3 4]
[5 6 7 8]
<class 'numpy.ndarray'> <class 'numpy.ndarray'>


In [22]:
np3 = np.arange(0,31,2)# np.arange
print(np3)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30]


In [23]:
np3

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [24]:
np4 = np.linspace(1,15,3)

In [25]:
print(np4)

[ 1.  8. 15.]


In [26]:
np4 = np.linspace(1,15,3)

In [27]:
print(np4)

[ 1.  8. 15.]


In [28]:
np4 = np.linspace(1,10,10)#np.linspace
print(np4)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [29]:
np4

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [30]:
np5 = np.zeros((5,))#np.zeros
print(np5)

[0. 0. 0. 0. 0.]


In [31]:
np6 = np.ones((5,))
print(np6)

[1.]


In [35]:
np6 = np.ones((5,))#np.ones
print(np6)

[1. 1. 1. 1. 1.]


In [33]:
np7 = np.ones((5,2))
print(np7)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [34]:
np7 = np.ones((5,3))
print(np7)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [36]:
listdata  = [[1,2,3,4,5],[6,7,8,9,10]]

In [37]:
np8 = np.array(listdata)

In [38]:
np8

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [39]:
print(np8)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [40]:
print("維度",np8.dim)

AttributeError: 'numpy.ndarray' object has no attribute 'dim'

In [41]:
print('維度',np8.dim)

AttributeError: 'numpy.ndarray' object has no attribute 'dim'

In [42]:
print("維度",np8.ndim)

維度 2


In [43]:
print("形狀",np8.shape)

形狀 (2, 5)


In [44]:
print("數量",np8.size)

數量 10


In [45]:
np9 = np.arange(1,21)

In [46]:
np9

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [47]:
np10 = np9.reshape(4,5)

In [48]:
np10

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [49]:
print(np10)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [50]:
no10a = np9.reshape(5,4)

In [51]:
np10a

NameError: name 'np10a' is not defined

In [52]:
np10a = np9.reshape(5,4)

In [53]:
np10a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [54]:
print(np10a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


In [55]:
np10 = np.arange(0,9)

In [56]:
print(np10)
print(np10[0])
print(np10[8])
print(np10[1:8])
print(np10[1:8:2])
print(np10[8:1:-1])
print(np10[:])
print(np10[:4])
print(np10[4:])




[0 1 2 3 4 5 6 7 8]
0
8
[1 2 3 4 5 6 7]
[1 3 5 7]
[8 7 6 5 4 3 2]
[0 1 2 3 4 5 6 7 8]
[0 1 2 3]
[4 5 6 7 8]


In [57]:
np11 = np.arrange(1,21).reshape(5,4)

AttributeError: module 'numpy' has no attribute 'arrange'

In [59]:
np11 = np.arange(1,21).reshape(5,4)

In [60]:
np11

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [61]:
np11[0,2]


3

In [62]:
np11[0,3]

4

In [63]:
np11[1,2]

7

In [67]:
print(np11[1:3,2])

print(np11[1:3,1:3])

print(np11[::2,::2])

print(np11[:,2])

print(np11[1,:])

print(np11[:,:])

[ 7 11]
[[ 6  7]
 [10 11]]
[[ 1  3]
 [ 9 11]
 [17 19]]
[ 3  7 11 15 19]
[5 6 7 8]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


In [68]:
print('1.產生2x30~1之間的隨機浮數n',
np.random.rand(2,3))
print('2.產生2x3常態分佈的隨機浮點數\n',
np.random.randn(2,3))
print('3.產生0~4(不含5)隨機整數\n',
np.random.randint(5))
print('4.產生2~4(不含5)5個隨機整數\n',
np.random.randint(2,5,[5]))
print('5.產生3個0~1之間的隨機浮n',
np.random.random(3), 'In',
np.random.random_sample(3), In',
np.random.sample(3))

SyntaxError: EOL while scanning string literal (2848371670.py, line 11)

In [69]:
print('1.產生2x30~1之間的隨機浮數n',
np.random.rand(2,3))
print('2.產生2x3常態分佈的隨機浮點數\n',
np.random.randn(2,3))
print('3.產生0~4(不含5)隨機整數\n',
np.random.randint(5))
print('4.產生2~4(不含5)5個隨機整數\n',
np.random.randint(2,5,[5]))
print('5.產生3個0~1之間的隨機浮\n',
np.random.random(3), '\n',
np.random.random_sample(3), '\n',
np.random.sample(3))

1.產生2x30~1之間的隨機浮數n [[0.31252533 0.07008053 0.38292203]
 [0.41597715 0.13434992 0.40645843]]
2.產生2x3常態分佈的隨機浮點數
 [[ 2.79413187 -1.38091613 -0.2655469 ]
 [ 0.47533964  1.01998659 -0.8107484 ]]
3.產生0~4(不含5)隨機整數
 2
4.產生2~4(不含5)5個隨機整數
 [2 3 4 3 2]
5.產生3個0~1之間的隨機浮
 [0.72650887 0.86953535 0.94496672] 
 [0.07719632 0.09080785 0.33458904] 
 [0.05008622 0.76979978 0.18126402]


In [70]:
np12 = np.genfromtxt('scores.csv', delimiter=',', skip_header=1)

In [71]:
np12

array([[ 1., 87., 85., 82.],
       [ 2., 92., 87., 90.],
       [ 3., 80., 91., 87.],
       [ 4., 78., 82., 95.],
       [ 5., 88., 89., 90.],
       [ 6., 82., 87., 88.],
       [ 7., 90., 92., 82.],
       [ 8., 87., 80., 90.],
       [ 9., 95., 78., 87.],
       [10., 90., 88., 95.],
       [11., 88., 89., 75.],
       [12., 82., 91., 66.],
       [13., 90., 82., 87.],
       [14., 87., 89., 92.],
       [15., 95., 87., 80.],
       [16., 90., 92., 78.],
       [17., 82., 80., 88.],
       [18., 90., 78., 93.],
       [19., 67., 87., 95.],
       [20., 91., 82., 88.],
       [21., 82., 81., 82.],
       [22., 79., 87., 90.],
       [23., 87., 92., 87.],
       [24., 92., 82., 95.],
       [25., 80., 90., 78.],
       [26., 78., 76., 91.],
       [27., 66., 90., 82.],
       [28., 89., 77., 89.],
       [29., 87., 95., 87.],
       [30., 73., 90., 92.]])

In [72]:
np13 = np.genfromtxt('205 pretest orginal data adjust', delimiter=',', skip_header=1)

OSError: 205 pretest orginal data adjust not found.

In [73]:
np13 = np.genfromtxt('205 pretest orginal data adjust', delimiter=',', skip_header=1)
np13

OSError: 205 pretest orginal data adjust not found.

In [74]:
np13 = np.genfromtxt('205.csv', delimiter=',', skip_header=1)

In [75]:
np13

array([[ 4.,  4.,  4., ..., nan, nan, nan],
       [ 3.,  3.,  4., ..., nan, nan, nan],
       [ 5.,  5.,  5., ..., nan, nan, nan],
       ...,
       [ 7.,  7.,  6., ..., nan, nan, nan],
       [ 6.,  6.,  5., ..., nan, nan, nan],
       [ 5.,  5.,  4., ..., nan, nan, nan]])

In [76]:
print(np13)

[[ 4.  4.  4. ... nan nan nan]
 [ 3.  3.  4. ... nan nan nan]
 [ 5.  5.  5. ... nan nan nan]
 ...
 [ 7.  7.  6. ... nan nan nan]
 [ 6.  6.  5. ... nan nan nan]
 [ 5.  5.  4. ... nan nan nan]]
